### ISSUE TITLE
Erroneous processing of MicroXPath // & ancestor axis (also * name tests)

### ISSUE THREAD

**Issue by uogbuji** [uogbuji/amara3-xml#9]
```
from amara3.uxml import html5
from amara3.uxml.treeutil import descendants, select_elements
from amara3.uxml import xml
from amara3.uxml.treeutil import *
from amara3.uxml.tree import *
from amara3.uxml.uxpath import context as xpathcontext, parse as xpathparse

import requests
resp = requests.get('http://garybyker.library.link/resource/5bLglR2qVao/')
root = html5.parse(resp.text)
xpathctx = xpathcontext(root)
ALL_IMAGES = xpathparse('//img')
it = ALL_IMAGES.compute(xpathctx)
i = next(it) #StopIteration
# root => {uxml.element (-9223363273091541553) "html" with 3 children}
# root.xml_children[2] => {uxml.element (-9223363273092099405) "body" with 10 children}

X = xpathparse('/html//img')
it = X.compute(xpathctx)
n = next(it)
```
Last 3 lines result in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uche/.local/pyenv/main/lib/python3.6/site-packages/amara3/uxml/uxpath/ast.py", line 313, in compute
    yield from self.relative.compute(new_ctx)
  File "/home/uche/.local/pyenv/main/lib/python3.6/site-packages/amara3/uxml/uxpath/ast.py", line 234, in compute
    yield from self.right.compute(new_ctx)
  File "/home/uche/.local/pyenv/main/lib/python3.6/site-packages/amara3/uxml/uxpath/ast.py", line 379, in compute
    to_process = list(child.xml_children) + to_process[1:]
AttributeError: 'comment' object has no attribute 'xml_children'
```
Note alternative works fine

```
imgs = [ e for e in descendants(root) if e.xml_name == 'img' ]
# imgs => [{uxml.element (8763762573951) "img" with 0 children}, {uxml.element (8763762576069) "img" with 0 children}, {uxml.element (8763762579471) "img" with 0 children}, {uxml.element (-9223363273092194223) "img" with 0 children}, {uxml.element (8763762583444) "img" with 0 children}, {uxml.element (-9223363273092209555) "img" with 0 children}]
```

Also not working:

```
PARENT_RESOURCE = xpathparse('ancestor::div[@class="thumbnail-holder"]/a/@href')
img = imgs[0]
imgctx = xpathcontext(img) #, force_root=False)
res = next(PARENT_RESOURCE.compute(imgctx), None)
```

Working alternative:

```
preparent, parent = img, img.xml_parent
while parent:
    if parent.xml_name == 'div' and 'thumbnail-holder' in parent.xml_attributes.get('class', ''):
        break
    preparent = parent
    parent = parent.xml_parent
```

**Comment by uogbuji** [comment]
OK I guess my free time allows for addressing ancient issues 😂

The page originally used to demo this problem is gone. The following updates the page and should also be easier to follow. The HTML content downloaded from the page used is attached as a file below, to ward against future bit rot, renamed a `.txt` file because Github doesn't like `.html`.

```python
from amara3.uxml import html5
from amara3.uxml.treeutil import descendants, select_elements
from amara3.uxml import xml
from amara3.uxml.treeutil import *
from amara3.uxml.tree import *
from amara3.uxml.uxpath import qquery
from amara3.uxml.uxpath import context as xpathcontext, parse as xpathparse

import requests

resp = requests.get('https://link.delawarelibrary.org/portal/The-African-trilogy--Things-fall-apart--No/_ANeWCgYmK4/')
html_el = html5.parse(resp.text)

# Explicitly set top element as context node
xpathctx = xpathcontext(html_el)
all_images_q = xpathparse('//img')
all_images = all_images_q.compute(xpathctx)
im = next(all_images)  # → StopIteration even thought he doc has images

# Same result using the helper interface
all_images = qquery(root, '//img')
im = next(all_images)  # → StopIteration

# Quick inspections
html_el  # → {uxml.element (276016044) "html" with 3 children}
html_el.xml_children[2]  # → {uxml.element (276038215) "body" with 12 children}

# Explicitly take the first descent, which clears up the root node muddle
# But unearths a new problem
all_images_q = xpathparse('/html//img')
all_images = all_images_q.compute(xpathctx)
n = next(all_images)  # → AttributeError: 'comment' object has no attribute 'xml_children'
```

[The African trilogy _ Things fall apart ; No longer at ease , and Arrow of God - Delaware County District Library.txt](https://github.com/uogbuji/amara3-xml/files/11452853/The.African.trilogy._.Things.fall.apart.No.longer.at.ease.and.Arrow.of.God.-.Delaware.County.District.Library.txt)

**Comment by uogbuji** [comment]
[595242f](https://github.com/uogbuji/amara3-xml/commit/595242f0faa39600a6fa7b396526dce00c0f7c84) fixes the comment node bug.

**Comment by uogbuji** [comment]
It seems the `//` problem is more fundamental. Basic test (not working)

```
from amara3.uxml import parse
from amara3.uxml.uxpath import context as xpathcontext, parse as xpathparse

top = parse('<a><b i="1.1">+2+</b></a>')
actx = xpathcontext(top)  # Context set to top a element
bctx = xpathcontext(top.xml_children[0])  # Context set to contained b element
all_b = xpathparse('//b')
list(all_b.compute(actx))  # → empty (incorrect)
list(all_b.compute(bctx))  # → empty (incorrect)
all_b = xpathparse('/a//b')  # Explicitly navigate to top
list(all_b.compute(actx))  # → correctly returns the b node
list(all_b.compute(bctx))  # → correctly returns the b node
```

Seems to be missing the step of navigating to root when it starts the expression. Let's see the AST:

```
print(xpathparse('//b'))  # → {AbsolutePath // child::b}
print(xpathparse('/a//b'))  # → {AbsolutePath / child::a//child::b}
```

**Comment by uogbuji** [comment]
While on this, I noticed element tests don't seem to work either—they select too much (include text nodes) e.g. //* was selecting all element and text nodes int he doc, rather than just all element nodes.

**Comment by uogbuji** [comment]
Both // and * cases seem to be fixed. Test cases added (included deleting some redundant test cases). Many other minor tweaks, addressing unreported bugs.
